import assert from "node:assert/strict";
import test from "node:test";
import { readFile, readdir } from "node:fs/promises";
import { randomUUID } from "node:crypto";
import { Pool } from "pg";
import { SystemService } from "./system-service";
import { CatchUpService } from "./catch-up-service";
import { ConversationSummaryService } from "./conversation-summary-service";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { InMemoryTransport } from "@modelcontextprotocol/sdk/inMemory.js";
import { createMcpServer } from "./mcp-server";

const integration = process.env.TEST_DATABASE_URL ? test : test.skip;
integration("episode review: four-month MCP return, retry, ownership and independent presence", async () => {
  const admin = new Pool({ connectionString: process.env.TEST_DATABASE_URL });
  const schema = `episode_${randomUUID().replaceAll("-", "")}`;
  await admin.query(`create schema ${schema}`);
  const pool = new Pool({ connectionString: process.env.TEST_DATABASE_URL, options: `-c search_path=${schema},public` });
  await pool.query(await readFile("db/baseline.sql","utf8"));
  for (const file of (await readdir("drizzle")).filter(f=>f.endsWith(".sql")).sort()) await pool.query(await readFile(`drizzle/${file}`,"utf8"));
  const owner = `review-eval:${randomUUID()}`, other = `review-eval:${randomUUID()}`;
  const system = new SystemService(pool), catchups = new CatchUpService(pool), summaries = new ConversationSummaryService(pool);
  const server = createMcpServer(owner,system,catchups,undefined,summaries);
  const client = new Client({ name: "synthetic-chatgpt", version: "1" });
  const [ct,st] = InMemoryTransport.createLinkedPair();
  await server.connect(st); await client.connect(ct);
  try {
    const person = (await system.createAlter(owner,{requestId:randomUUID(),name:"Synthetic returning person"},"WEB")).data;
    const host = (await system.createAlter(owner,{requestId:randomUUID(),name:"Synthetic host"},"WEB")).data;
    await pool.query("insert into pilot_account(owner_id,role,state) values($1,'OPERATOR','ACTIVE')",[owner]);
    await system.setSystemHost(owner,{requestId:randomUUID(),alterId:host.id,expectedVersion:null},"WEB");
    const previousEnd = new Date(); previousEnd.setMonth(previousEnd.getMonth()-4);
    await pool.query("insert into presence_period(owner_id,alter_id,kind,started_at,ended_at) values($1,$2,'FRONTING',$3::timestamptz-interval '1 day',$3)",[owner,person.id,previousEnd]);
    await pool.query("insert into system_note(owner_id,alter_id,body) select $1,$2,'Synthetic interval record ' || n from generate_series(1,125) n",[owner,person.id]);
    const args = {requestId:randomUUID(),alterId:person.id};
    const started = await client.callTool({name:"start_fronting_episode",arguments:args});
    assert.ok(!started.isError, JSON.stringify(started));
    const session = await catchups.openForCurrentFronter(owner);
    assert.ok(session); assert.equal(session.alterId,person.id);
    assert.equal(session.windowStart,previousEnd.toISOString());
    assert.ok(Date.parse(session.windowEnd)-Date.parse(session.windowStart)>110*86400000);
    const pageOne = await catchups.readEpisodeRecords(owner,session.id,undefined,50);
    const pageTwo = await catchups.readEpisodeRecords(owner,session.id,pageOne.nextCursor!,50);
    const pageThree = await catchups.readEpisodeRecords(owner,session.id,pageTwo.nextCursor!,50);
    assert.equal(pageThree.nextCursor,null);
    assert.equal(new Set([...pageOne.items,...pageTwo.items,...pageThree.items].map(item=>item.entryId)).size,125);
    assert.equal(pageThree.windowStart,session.windowStart);
    const repeated = await client.callTool({name:"start_fronting_episode",arguments:args});
    assert.ok(!repeated.isError); assert.equal((await catchups.openForCurrentFronter(owner))?.id,session.id);
    const before = await system.getCurrentPresence(owner);
    const input = {version:1 as const,requestId:randomUUID(),catchUpSessionId:session.id,alterId:person.id,expectedRevision:0,generatedAt:new Date().toISOString(),sourceClient:"Synthetic ChatGPT",timeZone:"UTC",overview:"Synthetic overview",attentionNow:"Synthetic attention",significantChanges:"Synthetic changes",coverage:"Only fixture context. ChatGPT memory unavailable.",sourceReferences:[{kind:"DIDDY" as const,reference:session.id}]};
    await assert.rejects(summaries.saveEpisodeReview(owner,{...input,alterId:host.id}),/NOT_FOUND/);
    await assert.rejects(summaries.saveEpisodeReview(other,input));
    assert.equal((await system.getCurrentPresence(owner)).fronting[0].id,before.fronting[0].id);
    const saved = await client.callTool({name:"save_episode_review_v1",arguments:input});
    assert.ok(!saved.isError,JSON.stringify(saved));
    const retries = await Promise.all([summaries.saveEpisodeReview(owner,input),summaries.saveEpisodeReview(owner,input)]);
    assert.ok(retries.every(r=>r.replayed));
    const review = await summaries.forSession(owner,session.id);
    assert.equal(review.revision,1); assert.match(review.review!.summary,/Synthetic overview/);
    assert.equal(review.review!.coverage,input.coverage);
    await assert.rejects(summaries.saveEpisodeReview(owner,{...input,requestId:randomUUID()}),/CONFLICT/);
    assert.deepEqual(await system.getCurrentPresence(owner),before);
    const receipt = (await pool.query("select result from mutation_receipt where owner_id=$1 and request_id=$2",[owner,input.requestId])).rows[0].result;
    assert.ok(!JSON.stringify(receipt).includes("Synthetic overview"));
    const first = (await system.createAlter(owner,{requestId:randomUUID(),name:"Synthetic first arrival"},"WEB")).data;
    const arrival = await system.startFrontingEpisode(owner,{requestId:randomUUID(),alterId:first.id},"WEB");
    const firstSession = await catchups.openForCurrentFronter(owner,arrival.data.id);
    assert.ok(firstSession); assert.equal(firstSession.windowStart,undefined);
    await summaries.saveEpisodeReview(owner,{...input,requestId:randomUUID(),catchUpSessionId:firstSession.id,alterId:first.id});
    assert.equal((await summaries.forSession(owner,firstSession.id)).review!.startAt,null);
    assert.equal((await system.getCurrentPresence(owner)).fronting.length,2);
    assert.equal((await catchups.openForCurrentFronter(owner))?.alterId,first.id);
  } finally {
    await client.close(); await server.close();
    await pool.query("select set_config('app.pilot_purge',$1,false)",[owner]);
    await pool.query("delete from app_user where id=any($1::text[])",[[owner,other]]);
    await pool.end(); await admin.query(`drop schema ${schema} cascade`); await admin.end();
  }
});
